### ISSUE TITLE
error: Sorry, `scope.generatorType` must be defined.

### ISSUE THREAD

**Issue by tjwebb** [balderdashy/sails-generate#8]
In my `before` function, I am explicitly setting `scope.generatorType`.

**Comment by CWyrtzen** [comment]
Hi @tjwebb is this still an issue?

**Comment by tjwebb** [comment]
whew... I have no idea. We can re-visit if someone else files.

**Comment by CWyrtzen** [comment]
"Revisit", you mean close? And then reopen if someone else needs it at a later date? Or did you mean something else?

**Comment by tjwebb** [comment]
Yea, sorry for not being clear. Feel free to close it now, and we can
reopen if someone else confirms it.

**Comment by CWyrtzen** [comment]
thx @tjwebb ~

**Comment by sidbenac** [comment]
Hi,

I tried to fork the repository and i have this error when I execute : 

node ./bin
did i missed something ?
thx
